#!/bin/bash 
NAME="olfy"                                 # Name of the application 
DJANGODIR=/home/sushant/Desktop/django_project            # Django project directory 
SOCKFILE=/home/sushant/Desktop/django_project/run/gunicorn.sock # we will communicte using this unix socket 
USER=sushant                                       # the user to run as 
GROUP=sushant                                    # the group to run as 
NUM_WORKERS=7                                    # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=django_project.settings            # which settings file should Django use 
DJANGO_WSGI_MODULE=django_project.wsgi                    # WSGI module name 

cd $DJANGODIR 
source ~/anaconda3/etc/profile.d/conda.sh
conda activate my-rdkit-env
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH    
# Create the run directory if it doesn't exist 
RUNDIR=$(dirname $SOCKFILE) 
test -d $RUNDIR || mkdir -p $RUNDIR 
  
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=- \
--timeout 3600