#!/bin/bash 
  
NAME="olfy"                                 # Name of the application 
DJANGODIR=/home/sushant/Desktop/django_project            # Django project directory 
SOCKFILE=localhost:8000 # we will communicte using this unix socket 
USER=sushant                                       # the user to run as 
GROUP=sushant                                    # the group to run as 
NUM_WORKERS=6                                    # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=django_project.settings            # which settings file should Django use 
DJANGO_WSGI_MODULE=django_project.wsgi                    # WSGI module name 
  
echo "Starting $NAME as `whoami`" 

cd $DJANGODIR 
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH    
# Create the run directory if it doesn't exist 
RUNDIR=$(dirname $SOCKFILE) 
test -d $RUNDIR || mkdir -p $RUNDIR 
  
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec gunicorn ${DJANGO_WSGI_MODULE}:application \ 
 --name $NAME \ 
 --workers $NUM_WORKERS \ 
 --user=$USER --group=$GROUP \ 
 --bind=$SOCKFILE \ 
 --log-level=debug \ 
 --log-file=- 